### ISSUE TITLE
Request npm package name

### ISSUE THREAD

**Issue by sxzz** [zekunjin/unplugin-replace#1]
Hello,

I've noticed that the package name `unplugin-replace` on npm has already been registered by this project. On behalf of the unplugin community, I kindly request that you could transfer this package name to us. We would be immensely grateful for your help.

Here is a link to a similar project within the unplugin community: https://github.com/unplugin/unplugin-replace

Looking forward to your response, thank you very much!

---

你好，

我刚刚注意到 npm 上的 `unplugin-replace` 包已经被本项目注册。我代表 unplugin 社区恳请您能将这个包名转让给我们。如果能够如此帮助，我们将不胜感激。

这是 unplugin 社区的一个类似项目链接：https://github.com/unplugin/unplugin-replace

期待您的回复，非常感谢！

**Comment by tmg0** [comment]
Of course, I'll change the name of it on npm.

I am very happy that the unplugin community has already paid attention to this requirement.

By the way, I also noticed the `@rollup/plugin-replace` plugin, but it seems like it can't perform regex match replacements. Is there any good solution?

**Comment by sxzz** [comment]
I will support regex patterns in `unplugin-replace`.

**Comment by tmg0** [comment]
Thanks for response！I'm really looking forward to seeing this feature.

**Comment by sxzz** [comment]
Thank you for generously giving up this package name. Best wishes.

**Comment by sxzz** [comment]
Regex patterns are now supported in `unplugin-replace`. I'll publish it on npm later today.

**Comment by tmg0** [comment]
Wow, such a quick improvement! 🚀
